"""
LaunchBox Notes Updater - Two-Pass Workflow
===========================================
Automatically discovers all XML files in a folder.
Updated XML files are saved alongside the originals with an _updated suffix.

PASS 1 (MODE = "review"):
    Fuzzy-matches scanned game names against LaunchBox <Title> fields
    across ALL XML files found in XML_FOLDER and writes matches_review.csv.

PASS 2 (MODE = "apply"):
    Reads your approved matches_review.csv and appends PDF citations
    to the <Notes> field of each confirmed match across all XML files.

Requirements:
    pip install thefuzz python-Levenshtein lxml

Usage:
    1. Set XML_FOLDER to the folder containing your XML files
    2. Set MODE = "review" and run - generates matches_review.csv
    3. Edit APPROVED_TITLE column - clear a row to skip that game
    4. Set MODE = "apply" and run - writes one _updated XML per input file
"""

import os
import sys
import re
import csv
from collections import defaultdict

# =============================================================================
# CONFIGURE THESE SETTINGS BEFORE RUNNING
# =============================================================================

MODE = "review"
# "review" = generate CSV for checking   |   "apply" = write updated XML files

GAMES_FOUND_TXT = r"C:\Users\guyut\OneDrive\Desktop\exowork\games_found_pczone.txt"
# Output file from scan_games.py

XML_FOLDER = r"C:\Users\guyut\OneDrive\Desktop\exowork\xml"
# Folder containing your LaunchBox XML files.
# ALL .xml files found here will be loaded automatically.
# Updated files will be saved in the same folder as originalname_updated.xml
# Files already ending in _updated.xml are automatically skipped.

REVIEW_CSV = r"C:\Users\guyut\OneDrive\Desktop\exowork\matches_review.csv"
# Generated by "review" pass, edited by you, read by "apply" pass

# =============================================================================
# OPTIONAL SETTINGS
# =============================================================================

FUZZY_THRESHOLD = 90
# Match strictness 0-100. Lower = more matches but more false positives.

# =============================================================================


def install_if_missing(package, import_name=None):
    import importlib
    import subprocess
    name = import_name if import_name else package
    try:
        importlib.import_module(name)
    except ImportError:
        print("Installing " + package + "...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", package])


# -----------------------------------------------------------------------------
# DISCOVER XML FILES
# -----------------------------------------------------------------------------

def discover_xml_files(folder):
    """
    Find all .xml files in folder, excluding any already ending in _updated.xml.
    Returns list of (input_path, output_path) tuples.
    """
    if not os.path.isdir(folder):
        print("ERROR: XML_FOLDER not found:")
        print("  " + folder)
        sys.exit(1)

    pairs = []
    for filename in sorted(os.listdir(folder)):
        if not filename.lower().endswith(".xml"):
            continue
        # Skip files we previously generated
        if filename.lower().endswith("_updated.xml"):
            continue
        input_path  = os.path.join(folder, filename)
        base        = os.path.splitext(filename)[0]
        output_path = os.path.join(folder, base + "_updated.xml")
        pairs.append((input_path, output_path))

    return pairs


# -----------------------------------------------------------------------------
# PARSE games_found.txt
# -----------------------------------------------------------------------------

def parse_games_found(path):
    """
    Reads games_found.txt and returns:
        { scanned_game_name: { pdf_filename: [page_strings] } }
    """
    games = defaultdict(lambda: defaultdict(list))

    with open(path, encoding="utf-8") as fh:
        content = fh.read()

    master_match = re.search(r"MASTER INDEX.*?\n=+\n(.*)", content, re.DOTALL)

    if master_match:
        body = master_match.group(1)
        current_game = None
        for line in body.splitlines():
            if not line.strip():
                continue
            if not line[0].isspace():
                current_game = line.strip()
            elif current_game:
                for sep in ("--", "\u2014"):
                    if sep in line:
                        parts = line.split(sep, 1)
                        pdf = parts[0].strip()
                        pages = re.sub(r"^p\.\s*", "", parts[1].strip())
                        if pdf:
                            games[current_game][pdf].append(pages)
                        break
    else:
        print("Note: MASTER INDEX section not found - using per-file section.")
        current_pdf = None
        for line in content.splitlines():
            stripped = line.strip()
            if re.match(r"^\S.*\.pdf$", stripped, re.IGNORECASE):
                current_pdf = stripped
            elif current_pdf and "p." in line:
                for sep in ("--", "\u2014"):
                    if sep in line:
                        parts = line.split(sep, 1)
                        game = parts[0].strip()
                        pages = re.sub(r"^p\.\s*", "", parts[1].strip())
                        if game:
                            games[game][current_pdf].append(pages)
                        break

    return {k: dict(v) for k, v in games.items()}


# -----------------------------------------------------------------------------
# LOAD LAUNCHBOX XML
# -----------------------------------------------------------------------------

def load_xml(path):
    from lxml import etree
    parser = etree.XMLParser(remove_blank_text=False)
    tree = etree.parse(path, parser)
    root = tree.getroot()
    elems = root.findall(".//Game")
    if not elems:
        elems = root.findall("Game")
    lb_titles = {}
    for elem in elems:
        t = elem.find("Title")
        if t is not None and t.text:
            lb_titles[t.text] = elem
    return tree, lb_titles


# -----------------------------------------------------------------------------
# FUZZY MATCHING
# -----------------------------------------------------------------------------

def normalize(name):
    n = name.lower()
    n = re.sub(r"\s*[\(\[].*?[\)\]]", "", n)
    n = re.sub(r"[^a-z0-9\s]", "", n)
    n = re.sub(r"\b(the|a|an)\b", "", n)
    return re.sub(r"\s+", " ", n).strip()


def find_top_matches(query, candidates, threshold, n=3):
    from thefuzz import fuzz, process
    q_norm = normalize(query)
    norm_map = {normalize(c): c for c in candidates}
    results = process.extract(
        q_norm,
        list(norm_map.keys()),
        scorer=fuzz.token_sort_ratio,
        limit=n
    )
    return [(norm_map[r[0]], r[1]) for r in results if r[1] >= threshold]


# -----------------------------------------------------------------------------
# PASS 1 - GENERATE REVIEW CSV
# -----------------------------------------------------------------------------

def run_review(game_refs, all_xml_data, review_csv, threshold):
    """
    Matches scanned games against titles from ALL loaded XML files combined.

    CSV columns:
        SCANNED_NAME   - game name found in PDFs (do not edit)
        APPROVED_TITLE - LaunchBox title to update (EDIT THIS COLUMN)
        XML_FILE       - which XML file this match came from (do not edit)
        MATCH_SCORE    - confidence 0-100, "NO MATCH" if nothing found
        ALTERNATIVE_1  - second best match (may be from a different XML)
        ALTERNATIVE_2  - third best match
        PDF_REFS       - page references from the scan (do not edit)

    How to edit:
        - APPROVED_TITLE is pre-filled with the best fuzzy guess
        - Change APPROVED_TITLE if it is wrong
        - Clear APPROVED_TITLE to skip that game entirely
        - XML_FILE tells you which file will be updated for that row
    """
    install_if_missing("thefuzz", "thefuzz")
    install_if_missing("python-Levenshtein", "Levenshtein")

    # Build combined title -> xml_path map across all XML files
    # If the same title exists in multiple XMLs, first one wins
    combined_titles = {}
    for xml_path, (tree, lb_titles) in all_xml_data.items():
        for title in lb_titles:
            if title not in combined_titles:
                combined_titles[title] = xml_path

    print("")
    print("Matching " + str(len(game_refs)) + " scanned games against "
          + str(len(combined_titles)) + " titles across "
          + str(len(all_xml_data)) + " XML file(s)  (threshold=" + str(threshold) + ")")
    print("")

    rows = []
    no_match_count = 0

    for scanned in sorted(game_refs.keys()):
        pdf_refs = game_refs[scanned]
        refs_str = " | ".join(
            pdf + ": p." + ",".join(pages)
            for pdf, pages in sorted(pdf_refs.items())
        )

        matches = find_top_matches(scanned, combined_titles.keys(), threshold, n=3)

        if not matches:
            no_match_count += 1
            rows.append({
                "SCANNED_NAME":   scanned,
                "APPROVED_TITLE": "",
                "XML_FILE":       "NO MATCH",
                "MATCH_SCORE":    "NO MATCH",
                "ALTERNATIVE_1":  "",
                "ALTERNATIVE_2":  "",
                "PDF_REFS":       refs_str,
            })
            print("  [NO MATCH]     " + scanned)
        else:
            best_title, best_score = matches[0]
            best_xml = combined_titles[best_title]

            def alt_str(m):
                return m[0] + " [" + os.path.basename(combined_titles[m[0]]) + "]"

            alt1 = alt_str(matches[1]) if len(matches) > 1 else ""
            alt2 = alt_str(matches[2]) if len(matches) > 2 else ""
            score_str = "(exact)" if best_score == 100 else "(" + str(best_score) + "%)"
            xml_short = os.path.basename(best_xml)
            print("  [MATCH " + score_str + "]  '" + scanned + "'  ->  '" + best_title + "'  [" + xml_short + "]")
            rows.append({
                "SCANNED_NAME":   scanned,
                "APPROVED_TITLE": best_title,
                "XML_FILE":       best_xml,
                "MATCH_SCORE":    best_score,
                "ALTERNATIVE_1":  alt1,
                "ALTERNATIVE_2":  alt2,
                "PDF_REFS":       refs_str,
            })

    fieldnames = [
        "SCANNED_NAME", "APPROVED_TITLE", "XML_FILE", "MATCH_SCORE",
        "ALTERNATIVE_1", "ALTERNATIVE_2", "PDF_REFS"
    ]
    with open(review_csv, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    matched_count = len(game_refs) - no_match_count
    print("")
    print("=" * 60)
    print("Total scanned:         " + str(len(game_refs)))
    print("Matched (pre-filled):  " + str(matched_count))
    print("No match found:        " + str(no_match_count))
    print("")
    print("Review CSV saved to:")
    print("  " + review_csv)
    print("")
    print("Next steps:")
    print("  1. Open matches_review.csv in Excel or a text editor")
    print("  2. Check APPROVED_TITLE - edit if wrong, clear to skip")
    print("  3. XML_FILE shows which XML will be updated for each row")
    print("  4. Save the CSV")
    print("  5. Change MODE = 'apply' and run again")
    print("")


# -----------------------------------------------------------------------------
# PASS 2 - APPLY APPROVED MATCHES TO XML FILES
# -----------------------------------------------------------------------------

def build_note_block(pdf_refs):
    lines = [""]
    for pdf, pages in sorted(pdf_refs.items()):
        lines.append("  * " + pdf + "  p. " + ", ".join(pages))
    return "\n".join(lines)


def note_already_added(existing, pdf_refs):
    if not existing:
        return False
    return any(pdf in existing for pdf in pdf_refs)


def run_apply(game_refs, all_xml_data, xml_output_map, review_csv):
    from lxml import etree

    if not os.path.isfile(review_csv):
        print("ERROR: Review CSV not found:")
        print("  " + review_csv)
        print("Run with MODE = 'review' first to generate it.")
        sys.exit(1)

    # Group approved matches by XML input file
    approved_by_xml = defaultdict(dict)
    skipped_blank = []

    with open(review_csv, newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            scanned  = row["SCANNED_NAME"].strip()
            title    = row["APPROVED_TITLE"].strip()
            xml_file = row.get("XML_FILE", "").strip()
            if title and xml_file and xml_file != "NO MATCH":
                approved_by_xml[xml_file][scanned] = title
            else:
                skipped_blank.append(scanned)

    total_approved = sum(len(v) for v in approved_by_xml.values())
    print("")
    print("Approved matches to apply:  " + str(total_approved))
    print("Skipped (blank title):      " + str(len(skipped_blank)))

    total_applied = 0
    total_already = 0
    total_not_found = []

    for xml_input, output_xml in xml_output_map.items():
        if xml_input not in all_xml_data:
            continue

        approved = approved_by_xml.get(xml_input, {})
        if not approved:
            print("")
            print("[" + os.path.basename(xml_input) + "] No approved matches - skipping.")
            continue

        print("")
        print("[" + os.path.basename(xml_input) + "] Applying "
              + str(len(approved)) + " match(es)...")

        tree, lb_titles = all_xml_data[xml_input]
        applied    = 0
        already_done = 0
        not_in_xml = []

        for scanned, lb_title in sorted(approved.items()):
            pdf_refs = game_refs.get(scanned)
            if not pdf_refs:
                print("  [WARN] '" + scanned + "' not in games_found.txt - skipping")
                continue

            elem = lb_titles.get(lb_title)
            if elem is None:
                not_in_xml.append(lb_title)
                print("  [WARN] '" + lb_title + "' not found in XML - skipping")
                continue

            notes_el = elem.find("Notes")
            existing = (notes_el.text or "") if notes_el is not None else ""

            if note_already_added(existing, pdf_refs):
                print("  [SKIP]    '" + lb_title + "' - references already in Notes")
                already_done += 1
                continue

            note_block = build_note_block(pdf_refs)
            new_notes  = existing.rstrip() + note_block

            if notes_el is None:
                notes_el = etree.SubElement(elem, "Notes")
            notes_el.text = new_notes

            refs_summary = ", ".join(sorted(pdf_refs))
            print("  [UPDATED] '" + lb_title + "'  <-  " + refs_summary)
            applied += 1

        print("  Updated: " + str(applied) + "  |  Already done: " + str(already_done))

        if not_in_xml:
            print("  Not found in XML: " + str(len(not_in_xml)))
            for t in not_in_xml:
                print("    - " + t)
            total_not_found.extend(not_in_xml)

        if applied == 0:
            print("  No changes to write for this file.")
        else:
            tree.write(output_xml, pretty_print=True, xml_declaration=True, encoding="utf-8")
            print("  Saved to: " + output_xml)

        total_applied += applied
        total_already += already_done

    print("")
    print("=" * 60)
    print("Total updated:      " + str(total_applied))
    print("Total already done: " + str(total_already))
    print("Total skipped:      " + str(len(skipped_blank)))
    if total_not_found:
        print("Total not in XML:   " + str(len(total_not_found)))
    print("")
    print("WARNING: Original XML files were NOT modified.")
    print("Review the _updated files before replacing your originals.")


# -----------------------------------------------------------------------------
# MAIN
# -----------------------------------------------------------------------------

def main():
    install_if_missing("thefuzz", "thefuzz")
    install_if_missing("python-Levenshtein", "Levenshtein")
    install_if_missing("lxml")

    if not os.path.isfile(GAMES_FOUND_TXT):
        print("ERROR: GAMES_FOUND_TXT not found:")
        print("  " + GAMES_FOUND_TXT)
        sys.exit(1)

    # Auto-discover XML files
    xml_pairs = discover_xml_files(XML_FOLDER)
    if not xml_pairs:
        print("ERROR: No XML files found in XML_FOLDER:")
        print("  " + XML_FOLDER)
        sys.exit(1)

    xml_output_map = {inp: out for inp, out in xml_pairs}

    print("")
    print("Reading:  " + GAMES_FOUND_TXT)
    game_refs = parse_games_found(GAMES_FOUND_TXT)
    print("  " + str(len(game_refs)) + " unique game(s) found in scan results.")

    # Load all XML files
    all_xml_data = {}
    total_titles = 0
    print("")
    print("Loading XML files from: " + XML_FOLDER)
    for input_xml, output_xml in xml_pairs:
        print("  " + os.path.basename(input_xml) + " ...", end="")
        tree, lb_titles = load_xml(input_xml)
        all_xml_data[input_xml] = (tree, lb_titles)
        print(" " + str(len(lb_titles)) + " titles")
        total_titles += len(lb_titles)
    print("  " + str(len(xml_pairs)) + " file(s), "
          + str(total_titles) + " total titles.")

    if MODE == "review":
        run_review(game_refs, all_xml_data, REVIEW_CSV, FUZZY_THRESHOLD)

    elif MODE == "apply":
        run_apply(game_refs, all_xml_data, xml_output_map, REVIEW_CSV)

    else:
        print("ERROR: Unknown MODE '" + MODE + "'.")
        print("Set MODE to 'review' or 'apply' at the top of the script.")
        sys.exit(1)


if __name__ == "__main__":
    main()